version: '2'

services: 
  frontend:
    build: front
    ports: 
      - "4200:4200"
    container_name: solinc-front
    restart: always

  backend:
    build: back
    ports: 
      - "3333:3333"
    container_name: solinc-back
    restart: always
    links: 
     - database

  database:
    build: db
    container_name: solinc-db
    restart: always